import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { organisationService } from '../services/api';
import { FiActivity, FiArrowRight, FiTrendingDown, FiUsers } from 'react-icons/fi';
import { Card, Loading, Title } from './OrganisationAnalytics';

export default function OrganisationPortal() {
  const [data, setData] = useState(null);
  useEffect(() => { organisationService.getDashboard().then(setData); }, []);
  if (!data) return <Loading />;
  const current = Number(data.currentMonthEmissions), previous = Number(data.previousMonthEmissions);
  const percent = previous ? ((current - previous) / previous * 100).toFixed(1) : '—';
  return <div className="mx-auto max-w-7xl space-y-6"><Title eyebrow="Organisation overview" title={`Welcome to ${data.organisationName}`} text="Your central workspace for team participation, carbon intelligence and reporting."/><section className="rounded-2xl border border-emerald-400/25 bg-emerald-400/10 px-5 py-4"><p className="text-xs font-bold uppercase tracking-wider text-emerald-300">Invite employees securely</p><p className="mt-1 text-sm text-slate-300">Company join code: <span className="ml-2 rounded-lg bg-slate-950 px-3 py-1 font-mono font-bold text-emerald-300">{data.joinCode}</span></p></section><section className="grid gap-5 md:grid-cols-3"><Stat icon={<FiActivity/>} label="This month" value={`${current.toFixed(1)} kg`} text="CO₂e reported"/><Stat icon={<FiUsers/>} label="Active members" value={data.employees.length} text="in your workspace"/><Stat icon={<FiTrendingDown/>} label="vs last month" value={percent === '—' ? '—' : `${percent}%`} text={`${previous} kg in the previous month`}/></section><section className="grid gap-6 lg:grid-cols-2"><Card title="Run your sustainability programme"><p className="text-sm leading-6 text-slate-400">Employees join with the company code, their employee ID, department and designation. Their daily activity logs feed the team totals securely.</p><div className="mt-5 flex flex-wrap gap-3"><Action to="/organisation/activity" label="Log an activity"/><Action to="/organisation/people" label="View people & teams"/></div></Card><Card title="Reporting at a glance"><dl className="space-y-3 text-sm"><Row label="Current-month emissions" value={`${data.currentMonthEmissions} kg CO₂e`}/><Row label="Previous-month emissions" value={`${data.previousMonthEmissions} kg CO₂e`}/><Row label="Tracked categories" value={data.categoryBreakdown.filter(x=>Number(x.totalCo2e)>0).length}/></dl><Link to="/organisation/reports" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-emerald-400 no-underline">Open CSR reporting <FiArrowRight/></Link></Card></section></div>;
}
function Stat({icon,label,value,text}){return <article className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><span className="text-emerald-400">{icon}</span><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-400">{text}</p></article>}; function Action({to,label}){return <Link to={to} className="rounded-lg bg-emerald-400 px-3 py-2 text-xs font-bold text-slate-950 no-underline hover:bg-emerald-300">{label}</Link>}; function Row({label,value}){return <div className="flex justify-between border-b border-slate-800 pb-3"><dt className="text-slate-400">{label}</dt><dd className="font-semibold">{value}</dd></div>}
